export const data = JSON.parse("{\"key\":\"v-0d2ca8b8\",\"path\":\"/02-database/02-jdbc/00-%E7%AE%80%E4%BB%8B.html\",\"title\":\"00-简介\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"00-简介\",\"date\":\"2023-08-16T22:05:41.000Z\",\"description\":\"参考资料 视频教程：https://www.bilibili.com/video/BV1Bt41137iB/ 一、JDBC 定义 Java DataBase Connectivity（Java 语言连接数据库），是 SUN 公司制定的一套接口（interface） 因为每一个数据库的底层实现原理都不一样，Oracle、MySQL、SqlServer 等...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/02-database/02-jdbc/00-%E7%AE%80%E4%BB%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"零号星球图书馆\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"00-简介\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"参考资料 视频教程：https://www.bilibili.com/video/BV1Bt41137iB/ 一、JDBC 定义 Java DataBase Connectivity（Java 语言连接数据库），是 SUN 公司制定的一套接口（interface） 因为每一个数据库的底层实现原理都不一样，Oracle、MySQL、SqlServer 等...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"LHP\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-08-16T22:05:41.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"00-简介\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-08-16T22:05:41.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"LHP\\\",\\\"url\\\":\\\"http://152.136.173.53:8090/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、JDBC 定义\",\"slug\":\"一、jdbc-定义\",\"link\":\"#一、jdbc-定义\",\"children\":[]},{\"level\":2,\"title\":\"二、准备工作\",\"slug\":\"二、准备工作\",\"link\":\"#二、准备工作\",\"children\":[]},{\"level\":2,\"title\":\"三、JDBC 编程六步（重要）\",\"slug\":\"三、jdbc-编程六步-重要\",\"link\":\"#三、jdbc-编程六步-重要\",\"children\":[{\"level\":3,\"title\":\"第一步：注册驱动\",\"slug\":\"第一步-注册驱动\",\"link\":\"#第一步-注册驱动\",\"children\":[]},{\"level\":3,\"title\":\"第二步：获取连接\",\"slug\":\"第二步-获取连接\",\"link\":\"#第二步-获取连接\",\"children\":[]},{\"level\":3,\"title\":\"第三步：获取数据库操作对象\",\"slug\":\"第三步-获取数据库操作对象\",\"link\":\"#第三步-获取数据库操作对象\",\"children\":[]},{\"level\":3,\"title\":\"第四步：执行 SQL 语句\",\"slug\":\"第四步-执行-sql-语句\",\"link\":\"#第四步-执行-sql-语句\",\"children\":[]},{\"level\":3,\"title\":\"第五步：处理查询结果集\",\"slug\":\"第五步-处理查询结果集\",\"link\":\"#第五步-处理查询结果集\",\"children\":[]},{\"level\":3,\"title\":\"第六步：释放资源\",\"slug\":\"第六步-释放资源\",\"link\":\"#第六步-释放资源\",\"children\":[]}]}],\"git\":{},\"readingTime\":{\"minutes\":1.46,\"words\":439},\"filePathRelative\":\"02-database/02-jdbc/00-关于IDEA.md\",\"localizedDate\":\"2023年8月17日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
