export const data = JSON.parse("{\"key\":\"v-46bdde2b\",\"path\":\"/database/jdbc/00-introduction.html\",\"title\":\"00-introduction\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"00-introduction\",\"date\":\"2023-08-16T22:05:41.000Z\",\"description\":\"一、JDBC 定义 Java DataBase Connectivity（Java 语言连接数据库），是 SUN 公司制定的一套接口（interface） 因为每一个数据库的底层实现原理都不一样，Oracle、MySQL、SqlServer 等数据库有自己的原理，每一个数据库产品都有自己独特的实现原理。 image.png 二、准备工作 先从官网下载 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/database/jdbc/00-introduction.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"零号星球图书馆\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"00-introduction\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、JDBC 定义 Java DataBase Connectivity（Java 语言连接数据库），是 SUN 公司制定的一套接口（interface） 因为每一个数据库的底层实现原理都不一样，Oracle、MySQL、SqlServer 等数据库有自己的原理，每一个数据库产品都有自己独特的实现原理。 image.png 二、准备工作 先从官网下载 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"LHP\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-08-16T22:05:41.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"00-introduction\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-08-16T22:05:41.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"LHP\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、JDBC 定义\",\"slug\":\"一、jdbc-定义\",\"link\":\"#一、jdbc-定义\",\"children\":[]},{\"level\":2,\"title\":\"二、准备工作\",\"slug\":\"二、准备工作\",\"link\":\"#二、准备工作\",\"children\":[]},{\"level\":2,\"title\":\"三、JDBC 编程六步（重要）\",\"slug\":\"三、jdbc-编程六步-重要\",\"link\":\"#三、jdbc-编程六步-重要\",\"children\":[{\"level\":3,\"title\":\"第一步：注册驱动\",\"slug\":\"第一步-注册驱动\",\"link\":\"#第一步-注册驱动\",\"children\":[]},{\"level\":3,\"title\":\"第二步：获取连接\",\"slug\":\"第二步-获取连接\",\"link\":\"#第二步-获取连接\",\"children\":[]},{\"level\":3,\"title\":\"第三步：获取数据库操作对象\",\"slug\":\"第三步-获取数据库操作对象\",\"link\":\"#第三步-获取数据库操作对象\",\"children\":[]},{\"level\":3,\"title\":\"第四步：执行 SQL 语句\",\"slug\":\"第四步-执行-sql-语句\",\"link\":\"#第四步-执行-sql-语句\",\"children\":[]},{\"level\":3,\"title\":\"第五步：处理查询结果集\",\"slug\":\"第五步-处理查询结果集\",\"link\":\"#第五步-处理查询结果集\",\"children\":[]},{\"level\":3,\"title\":\"第六步：释放资源\",\"slug\":\"第六步-释放资源\",\"link\":\"#第六步-释放资源\",\"children\":[]}]}],\"git\":{},\"readingTime\":{\"minutes\":1.42,\"words\":425},\"filePathRelative\":\"database/jdbc/00-关于IDEA.md\",\"localizedDate\":\"2023年8月17日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
